### PR TITLE
Feature batctl version autodetect

### LINKED ISSUE #50: Compatibility to batctl >= 2019.3
Hello together,
with batman-adv the batctl-option "-m <device>" is replaced with "meshif <device>" (see https://www.open-mesh.org/news/92).
As of now, this only triggers some deprecation warnings.

For fixing this replacing "-m" with "meshif" should work - but this probably breaks compatibility with BATMAN-ADV < 2019.3.

How should this be resolved?

Best regards
margau

### PR DESCRIPTION
**Pull request by TobleMiner**
Should fix #50 . Please test

### CODE REVIEW

**Comment by margau** [comment]
Works with batctl debian-2019.4-1 [batman-adv: 2018.3] without warnings.

**Comment by margau** [comment]
Seems not to work (Output:
` Jan  9 17:28:03 gw03 sh[3660]: Warning - option -m was deprecated and will be removed in the future`)

`batctl -v
batctl debian-2019.5-1 [batman-adv: 2019.4]`

I'll try to investigate further in the next days.

**Comment by AiyionPrime** [comment]
The fix is very simple, replace `-m` with `meshif` like their manpage suggests.
PR looks good, will test later.

**Comment by AiyionPrime** [comment]
And next time. I'll read the PR fully before answering half baked nonsense.
Sorry. PR looks good though, just merged it into something near master again, which is what I tested then on our supernode:
https://github.com/freifunkh/mesh-announce/commit/cf67269f62007ad07ed0740eec2ae131d763eb5a

I'd personally not care for versions before batctl 2019.3 and still just merge #64.

But this gets rid of the warning as well for batctl 2021.0
Tested on Debian Buster.

**Comment by AiyionPrime** [comment]
@TobleMiner maybe you find time to rebase this to master yourself?
If you'd have a look at my merge above, you could evaluate if you'd merged the same way and whether my tests need to be done again on your rebased PR.

**Comment by herbetom** [comment]
Made a PR for this PR: TobleMiner/mesh-announce/pull/1

I should probably just open a new PR :thinking: 

Didn't test it with something other then the batctl on my system (a current version) if this fallback really works, no idea

**Pull request closed without merging**
