### PR TITLE
add multi batman

### PR DESCRIPTION
**Pull request by genofire**
read values from another batman interfaces, too

### CODE REVIEW

**Comment by genofire** [comment]
the `statistics.d/traffic` is still just from the main interface -> feel free to create a forked PR from it.

**Comment by sap-dev** [comment]
:b

**Comment by mweinelt** [comment]
If this is supposed to be used in multidomain setups, whats your idea on the site/domain field?

**Comment by rotanid** [comment]
@genofire any comment on the question from @mweinelt ?

**Comment by rubo77** [comment]
There already is a solution working in https://github.com/freifunk-darmstadt/mesh-announce which is not up to date with the current branch.

Which will be the best solution to add multi-site support?

**Comment by genofire** [comment]
No idea make a PR so I could review the differences.

#32 is a better solution for the future ... I just have a **main** batman interface for generating a `node_id`, but for #27 we need a other solution to generate the it.

**Pull request closed without merging**
